# NumPy

In [1]:
import numpy as np

In [2]:
x = np.array([[3, 4], [8, 1], [2, 9]])

In [3]:
print(x.shape)

(3, 2)


In [4]:
y = x + 3.2

In [5]:
print(y)

[[ 6.2  7.2]
 [11.2  4.2]
 [ 5.2 12.2]]


In [6]:
i = np.array([[3, 4], [8, 1], [2, 9]])

In [7]:
z = np.ones_like(i)

In [8]:
print(z)

[[1 1]
 [1 1]
 [1 1]]


In [16]:
z.shape = (2,3)

In [18]:
arr = np.dot(i,z)

In [33]:
arr

array([[ 7,  7,  7],
       [ 9,  9,  9],
       [11, 11, 11]])

In [34]:
arr[0]

array([7, 7, 7])

In [36]:
np.sum(arr[0])

21